export enum Gender {
  Male = 'Male',
  Female = 'Female',
  Mx = 'Mx',
  Unknown = 'Unknown',
}

export enum EquipmentLevel {
  Raw = 'Raw',
  RawWithWraps = 'Raw with Wraps',
  Equipped = 'Equipped',
  Unknown = 'Unknown',
}

export enum AgeGroup {
  Youth = 'Youth',
  Youth1 = 'Youth 1',
  Youth2 = 'Youth 2',
  Youth3 = 'Youth 3',
  Teen = 'Teen',
  Teen1 = 'Teen 1',
  Teen2 = 'Teen 2',
  Teen3 = 'Teen 3',
  Junior = 'Junior',
  Open = 'Open',
  Master = 'Master',
  Master1 = 'Master 1',
  Master1A = 'Master 1A',
  Master1B = 'Master 1B',
  Master2 = 'Master 2',
  Master2A = 'Master 2A',
  Master2B = 'Master 2B',
  Master3 = 'Master 3',
  Master3A = 'Master 3A',
  Master3B = 'Master 3B',
  Master4 = 'Master 4',
  Master4A = 'Master 4A',
  Master4B = 'Master 4B',
  Master5 = 'Master 5',
  Master5A = 'Master 5A',
  Master5B = 'Master 5B',
  Master6 = 'Master 6',
  Master6A = 'Master 6A',
  Master6B = 'Master 6B',
  Guest = 'Guest',
  Collegiate = 'Collegiate',
  HighSchool = 'High School',
  HighSchoolVarsity = 'High School Varsity',
  HighSchoolJV = 'High School JV',
  Unknown = 'Unknown',
}
